import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import NavBar from "@/components/nav-bar";
import { NextIntlClientProvider } from "next-intl";
import {
  getLocale,
  getMessages,
  unstable_setRequestLocale,
} from "next-intl/server";
import { locales } from "@/navigation/config";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Mazeed ERP POC",
  description: "Generated by Mazeed ERP",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();
  console.log(locale, "local from layout possaac");
  // Providing all messages to the client
  // side is the easiest way to get started
  const messages = await getMessages({ locale });
  unstable_setRequestLocale(locale);

  return (
    <html lang={locale}>
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <NextIntlClientProvider messages={messages}>
            <NavBar />

            {children}
          </NextIntlClientProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
